"""
Complete MITRE ATT&CK Enterprise + ATLAS technique-to-tactic mapping.

Sourced from ATT&CK v16 (Jan 2025) and ATLAS v4.
Each entry maps a technique ID to its name and the tactic(s) it belongs to.
Multi-tactic techniques have multiple entries in their tactics list.
"""
from typing import List, Optional, Dict


# ==============================================================================
# ATT&CK ENTERPRISE TACTIC ORDER (official)
# ==============================================================================
ATTACK_TACTIC_ORDER = [
    "Reconnaissance",
    "Resource Development",
    "Initial Access",
    "Execution",
    "Persistence",
    "Privilege Escalation",
    "Defense Evasion",
    "Credential Access",
    "Discovery",
    "Lateral Movement",
    "Collection",
    "Command and Control",
    "Exfiltration",
    "Impact",
]

# ==============================================================================
# ATLAS TACTIC ORDER (official)
# ==============================================================================
ATLAS_TACTIC_ORDER = [
    "Reconnaissance",
    "Resource Development",
    "ML Model Access",
    "Initial Access",
    "Execution",
    "Persistence",
    "Defense Evasion",
    "Discovery",
    "Collection",
    "ML Attack Staging",
    "Exfiltration",
    "Impact",
]


# ==============================================================================
# ATT&CK ENTERPRISE TECHNIQUE MAP (v16)
# Format: "T####": {"name": "...", "tactics": ["...", ...]}
# Multi-tactic techniques are listed with ALL their tactics.
# Sub-techniques inherit parent tactics unless they differ.
# ==============================================================================
ATTACK_TECHNIQUE_MAP: Dict[str, Dict] = {
    # ── Reconnaissance ──────────────────────────────────────────────────────
    "T1595": {"name": "Active Scanning", "tactics": ["Reconnaissance"]},
    "T1595.001": {"name": "Scanning IP Blocks", "tactics": ["Reconnaissance"]},
    "T1595.002": {"name": "Vulnerability Scanning", "tactics": ["Reconnaissance"]},
    "T1595.003": {"name": "Wordlist Scanning", "tactics": ["Reconnaissance"]},
    "T1592": {"name": "Gather Victim Host Information", "tactics": ["Reconnaissance"]},
    "T1592.001": {"name": "Hardware", "tactics": ["Reconnaissance"]},
    "T1592.002": {"name": "Software", "tactics": ["Reconnaissance"]},
    "T1592.003": {"name": "Firmware", "tactics": ["Reconnaissance"]},
    "T1592.004": {"name": "Client Configurations", "tactics": ["Reconnaissance"]},
    "T1589": {"name": "Gather Victim Identity Information", "tactics": ["Reconnaissance"]},
    "T1589.001": {"name": "Credentials", "tactics": ["Reconnaissance"]},
    "T1589.002": {"name": "Email Addresses", "tactics": ["Reconnaissance"]},
    "T1589.003": {"name": "Employee Names", "tactics": ["Reconnaissance"]},
    "T1590": {"name": "Gather Victim Network Information", "tactics": ["Reconnaissance"]},
    "T1590.001": {"name": "Domain Properties", "tactics": ["Reconnaissance"]},
    "T1590.002": {"name": "DNS", "tactics": ["Reconnaissance"]},
    "T1590.003": {"name": "Network Trust Dependencies", "tactics": ["Reconnaissance"]},
    "T1590.004": {"name": "Network Topology", "tactics": ["Reconnaissance"]},
    "T1590.005": {"name": "IP Addresses", "tactics": ["Reconnaissance"]},
    "T1590.006": {"name": "Network Security Appliances", "tactics": ["Reconnaissance"]},
    "T1591": {"name": "Gather Victim Org Information", "tactics": ["Reconnaissance"]},
    "T1591.001": {"name": "Determine Physical Locations", "tactics": ["Reconnaissance"]},
    "T1591.002": {"name": "Business Relationships", "tactics": ["Reconnaissance"]},
    "T1591.003": {"name": "Identify Business Tempo", "tactics": ["Reconnaissance"]},
    "T1591.004": {"name": "Identify Roles", "tactics": ["Reconnaissance"]},
    "T1598": {"name": "Phishing for Information", "tactics": ["Reconnaissance"]},
    "T1598.001": {"name": "Spearphishing Service", "tactics": ["Reconnaissance"]},
    "T1598.002": {"name": "Spearphishing Attachment", "tactics": ["Reconnaissance"]},
    "T1598.003": {"name": "Spearphishing Link", "tactics": ["Reconnaissance"]},
    "T1598.004": {"name": "Spearphishing Voice", "tactics": ["Reconnaissance"]},
    "T1597": {"name": "Search Closed Sources", "tactics": ["Reconnaissance"]},
    "T1597.001": {"name": "Threat Intel Vendors", "tactics": ["Reconnaissance"]},
    "T1597.002": {"name": "Purchase Technical Data", "tactics": ["Reconnaissance"]},
    "T1596": {"name": "Search Open Technical Databases", "tactics": ["Reconnaissance"]},
    "T1596.001": {"name": "DNS/Passive DNS", "tactics": ["Reconnaissance"]},
    "T1596.002": {"name": "WHOIS", "tactics": ["Reconnaissance"]},
    "T1596.003": {"name": "Digital Certificates", "tactics": ["Reconnaissance"]},
    "T1596.004": {"name": "CDNs", "tactics": ["Reconnaissance"]},
    "T1596.005": {"name": "Scan Databases", "tactics": ["Reconnaissance"]},
    "T1593": {"name": "Search Open Websites/Domains", "tactics": ["Reconnaissance"]},
    "T1593.001": {"name": "Social Media", "tactics": ["Reconnaissance"]},
    "T1593.002": {"name": "Search Engines", "tactics": ["Reconnaissance"]},
    "T1593.003": {"name": "Code Repositories", "tactics": ["Reconnaissance"]},
    "T1594": {"name": "Search Victim-Owned Websites", "tactics": ["Reconnaissance"]},

    # ── Resource Development ────────────────────────────────────────────────
    "T1583": {"name": "Acquire Infrastructure", "tactics": ["Resource Development"]},
    "T1583.001": {"name": "Domains", "tactics": ["Resource Development"]},
    "T1583.002": {"name": "DNS Server", "tactics": ["Resource Development"]},
    "T1583.003": {"name": "Virtual Private Server", "tactics": ["Resource Development"]},
    "T1583.004": {"name": "Server", "tactics": ["Resource Development"]},
    "T1583.005": {"name": "Botnet", "tactics": ["Resource Development"]},
    "T1583.006": {"name": "Web Services", "tactics": ["Resource Development"]},
    "T1583.007": {"name": "Serverless", "tactics": ["Resource Development"]},
    "T1583.008": {"name": "Malvertising", "tactics": ["Resource Development"]},
    "T1586": {"name": "Compromise Accounts", "tactics": ["Resource Development"]},
    "T1586.001": {"name": "Social Media Accounts", "tactics": ["Resource Development"]},
    "T1586.002": {"name": "Email Accounts", "tactics": ["Resource Development"]},
    "T1586.003": {"name": "Cloud Accounts", "tactics": ["Resource Development"]},
    "T1584": {"name": "Compromise Infrastructure", "tactics": ["Resource Development"]},
    "T1584.001": {"name": "Domains", "tactics": ["Resource Development"]},
    "T1584.002": {"name": "DNS Server", "tactics": ["Resource Development"]},
    "T1584.003": {"name": "Virtual Private Server", "tactics": ["Resource Development"]},
    "T1584.004": {"name": "Server", "tactics": ["Resource Development"]},
    "T1584.005": {"name": "Botnet", "tactics": ["Resource Development"]},
    "T1584.006": {"name": "Web Services", "tactics": ["Resource Development"]},
    "T1584.007": {"name": "Serverless", "tactics": ["Resource Development"]},
    "T1587": {"name": "Develop Capabilities", "tactics": ["Resource Development"]},
    "T1587.001": {"name": "Malware", "tactics": ["Resource Development"]},
    "T1587.002": {"name": "Code Signing Certificates", "tactics": ["Resource Development"]},
    "T1587.003": {"name": "Digital Certificates", "tactics": ["Resource Development"]},
    "T1587.004": {"name": "Exploits", "tactics": ["Resource Development"]},
    "T1585": {"name": "Establish Accounts", "tactics": ["Resource Development"]},
    "T1585.001": {"name": "Social Media Accounts", "tactics": ["Resource Development"]},
    "T1585.002": {"name": "Email Accounts", "tactics": ["Resource Development"]},
    "T1585.003": {"name": "Cloud Accounts", "tactics": ["Resource Development"]},
    "T1588": {"name": "Obtain Capabilities", "tactics": ["Resource Development"]},
    "T1588.001": {"name": "Malware", "tactics": ["Resource Development"]},
    "T1588.002": {"name": "Tool", "tactics": ["Resource Development"]},
    "T1588.003": {"name": "Code Signing Certificates", "tactics": ["Resource Development"]},
    "T1588.004": {"name": "Digital Certificates", "tactics": ["Resource Development"]},
    "T1588.005": {"name": "Exploits", "tactics": ["Resource Development"]},
    "T1588.006": {"name": "Vulnerabilities", "tactics": ["Resource Development"]},
    "T1608": {"name": "Stage Capabilities", "tactics": ["Resource Development"]},
    "T1608.001": {"name": "Upload Malware", "tactics": ["Resource Development"]},
    "T1608.002": {"name": "Upload Tool", "tactics": ["Resource Development"]},
    "T1608.003": {"name": "Install Digital Certificate", "tactics": ["Resource Development"]},
    "T1608.004": {"name": "Drive-by Target", "tactics": ["Resource Development"]},
    "T1608.005": {"name": "Link Target", "tactics": ["Resource Development"]},
    "T1608.006": {"name": "SEO Poisoning", "tactics": ["Resource Development"]},

    # ── Initial Access ──────────────────────────────────────────────────────
    "T1189": {"name": "Drive-by Compromise", "tactics": ["Initial Access"]},
    "T1190": {"name": "Exploit Public-Facing Application", "tactics": ["Initial Access"]},
    "T1133": {"name": "External Remote Services", "tactics": ["Initial Access"]},
    "T1200": {"name": "Hardware Additions", "tactics": ["Initial Access"]},
    "T1566": {"name": "Phishing", "tactics": ["Initial Access"]},
    "T1566.001": {"name": "Spearphishing Attachment", "tactics": ["Initial Access"]},
    "T1566.002": {"name": "Spearphishing Link", "tactics": ["Initial Access"]},
    "T1566.003": {"name": "Spearphishing via Service", "tactics": ["Initial Access"]},
    "T1566.004": {"name": "Spearphishing Voice", "tactics": ["Initial Access"]},
    "T1091": {"name": "Replication Through Removable Media", "tactics": ["Initial Access", "Lateral Movement"]},
    "T1195": {"name": "Supply Chain Compromise", "tactics": ["Initial Access"]},
    "T1195.001": {"name": "Compromise Software Dependencies and Development Tools", "tactics": ["Initial Access"]},
    "T1195.002": {"name": "Compromise Software Supply Chain", "tactics": ["Initial Access"]},
    "T1195.003": {"name": "Compromise Hardware Supply Chain", "tactics": ["Initial Access"]},
    "T1199": {"name": "Trusted Relationship", "tactics": ["Initial Access"]},
    "T1078": {"name": "Valid Accounts", "tactics": ["Initial Access", "Defense Evasion", "Persistence", "Privilege Escalation"]},
    "T1078.001": {"name": "Default Accounts", "tactics": ["Initial Access", "Defense Evasion", "Persistence", "Privilege Escalation"]},
    "T1078.002": {"name": "Domain Accounts", "tactics": ["Initial Access", "Defense Evasion", "Persistence", "Privilege Escalation"]},
    "T1078.003": {"name": "Local Accounts", "tactics": ["Initial Access", "Defense Evasion", "Persistence", "Privilege Escalation"]},
    "T1078.004": {"name": "Cloud Accounts", "tactics": ["Initial Access", "Defense Evasion", "Persistence", "Privilege Escalation"]},

    # ── Execution ───────────────────────────────────────────────────────────
    "T1059": {"name": "Command and Scripting Interpreter", "tactics": ["Execution"]},
    "T1059.001": {"name": "PowerShell", "tactics": ["Execution"]},
    "T1059.002": {"name": "AppleScript", "tactics": ["Execution"]},
    "T1059.003": {"name": "Windows Command Shell", "tactics": ["Execution"]},
    "T1059.004": {"name": "Unix Shell", "tactics": ["Execution"]},
    "T1059.005": {"name": "Visual Basic", "tactics": ["Execution"]},
    "T1059.006": {"name": "Python", "tactics": ["Execution"]},
    "T1059.007": {"name": "JavaScript", "tactics": ["Execution"]},
    "T1059.008": {"name": "Network Device CLI", "tactics": ["Execution"]},
    "T1059.009": {"name": "Cloud API", "tactics": ["Execution"]},
    "T1059.010": {"name": "AutoHotKey & AutoIT", "tactics": ["Execution"]},
    "T1609": {"name": "Container Administration Command", "tactics": ["Execution"]},
    "T1610": {"name": "Deploy Container", "tactics": ["Execution", "Defense Evasion"]},
    "T1203": {"name": "Exploitation for Client Execution", "tactics": ["Execution"]},
    "T1559": {"name": "Inter-Process Communication", "tactics": ["Execution"]},
    "T1559.001": {"name": "Component Object Model", "tactics": ["Execution"]},
    "T1559.002": {"name": "Dynamic Data Exchange", "tactics": ["Execution"]},
    "T1559.003": {"name": "XPC Services", "tactics": ["Execution"]},
    "T1106": {"name": "Native API", "tactics": ["Execution"]},
    "T1053": {"name": "Scheduled Task/Job", "tactics": ["Execution", "Persistence", "Privilege Escalation"]},
    "T1053.002": {"name": "At", "tactics": ["Execution", "Persistence", "Privilege Escalation"]},
    "T1053.003": {"name": "Cron", "tactics": ["Execution", "Persistence", "Privilege Escalation"]},
    "T1053.005": {"name": "Scheduled Task", "tactics": ["Execution", "Persistence", "Privilege Escalation"]},
    "T1053.006": {"name": "Systemd Timers", "tactics": ["Execution", "Persistence", "Privilege Escalation"]},
    "T1053.007": {"name": "Container Orchestration Job", "tactics": ["Execution", "Persistence", "Privilege Escalation"]},
    "T1129": {"name": "Shared Modules", "tactics": ["Execution"]},
    "T1072": {"name": "Software Deployment Tools", "tactics": ["Execution", "Lateral Movement"]},
    "T1569": {"name": "System Services", "tactics": ["Execution"]},
    "T1569.001": {"name": "Launchctl", "tactics": ["Execution"]},
    "T1569.002": {"name": "Service Execution", "tactics": ["Execution"]},
    "T1204": {"name": "User Execution", "tactics": ["Execution"]},
    "T1204.001": {"name": "Malicious Link", "tactics": ["Execution"]},
    "T1204.002": {"name": "Malicious File", "tactics": ["Execution"]},
    "T1204.003": {"name": "Malicious Image", "tactics": ["Execution"]},
    "T1047": {"name": "Windows Management Instrumentation", "tactics": ["Execution"]},

    # ── Persistence ─────────────────────────────────────────────────────────
    "T1098": {"name": "Account Manipulation", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1098.001": {"name": "Additional Cloud Credentials", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1098.002": {"name": "Additional Email Delegate Permissions", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1098.003": {"name": "Additional Cloud Roles", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1098.004": {"name": "SSH Authorized Keys", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1098.005": {"name": "Device Registration", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1098.006": {"name": "Additional Container Cluster Roles", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1197": {"name": "BITS Jobs", "tactics": ["Persistence", "Defense Evasion"]},
    "T1547": {"name": "Boot or Logon Autostart Execution", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.001": {"name": "Registry Run Keys / Startup Folder", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.002": {"name": "Authentication Package", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.003": {"name": "Time Providers", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.004": {"name": "Winlogon Helper DLL", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.005": {"name": "Security Support Provider", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.006": {"name": "Kernel Modules and Extensions", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.008": {"name": "LSASS Driver", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.009": {"name": "Shortcut Modification", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.010": {"name": "Port Monitors", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.012": {"name": "Print Processors", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.013": {"name": "XDG Autostart Entries", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.014": {"name": "Active Setup", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1547.015": {"name": "Login Items", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1037": {"name": "Boot or Logon Initialization Scripts", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1037.001": {"name": "Logon Script (Windows)", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1037.002": {"name": "Login Hook", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1037.003": {"name": "Network Logon Script", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1037.004": {"name": "RC Scripts", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1037.005": {"name": "Startup Items", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1176": {"name": "Browser Extensions", "tactics": ["Persistence"]},
    "T1554": {"name": "Compromise Host Software Binary", "tactics": ["Persistence"]},
    "T1136": {"name": "Create Account", "tactics": ["Persistence"]},
    "T1136.001": {"name": "Local Account", "tactics": ["Persistence"]},
    "T1136.002": {"name": "Domain Account", "tactics": ["Persistence"]},
    "T1136.003": {"name": "Cloud Account", "tactics": ["Persistence"]},
    "T1543": {"name": "Create or Modify System Process", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1543.001": {"name": "Launch Agent", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1543.002": {"name": "Systemd Service", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1543.003": {"name": "Windows Service", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1543.004": {"name": "Launch Daemon", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1543.005": {"name": "Container Service", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546": {"name": "Event Triggered Execution", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.001": {"name": "Change Default File Association", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.002": {"name": "Screensaver", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.003": {"name": "Windows Management Instrumentation Event Subscription", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.004": {"name": "Unix Shell Configuration Modification", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.005": {"name": "Trap", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.006": {"name": "LC_LOAD_DYLIB Addition", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.008": {"name": "Accessibility Features", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.009": {"name": "AppCert DLLs", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.010": {"name": "AppInit DLLs", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.011": {"name": "Application Shimming", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.012": {"name": "Image File Execution Options Injection", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.013": {"name": "PowerShell Profile", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.014": {"name": "Emond", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.015": {"name": "Component Object Model Hijacking", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1546.016": {"name": "Installer Packages", "tactics": ["Persistence", "Privilege Escalation"]},
    "T1574": {"name": "Hijack Execution Flow", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.001": {"name": "DLL Search Order Hijacking", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.002": {"name": "DLL Side-Loading", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.004": {"name": "Dylib Hijacking", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.005": {"name": "Executable Installer File Permissions Weakness", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.006": {"name": "Dynamic Linker Hijacking", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.007": {"name": "Path Interception by PATH Environment Variable", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.008": {"name": "Path Interception by Search Order Hijacking", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.009": {"name": "Path Interception by Unquoted Path", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.010": {"name": "Services File Permissions Weakness", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.011": {"name": "Services Registry Permissions Weakness", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.012": {"name": "COR_PROFILER", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.013": {"name": "KernelCallbackTable", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1574.014": {"name": "AppDomainManager", "tactics": ["Persistence", "Privilege Escalation", "Defense Evasion"]},
    "T1137": {"name": "Office Application Startup", "tactics": ["Persistence"]},
    "T1137.001": {"name": "Office Template Macros", "tactics": ["Persistence"]},
    "T1137.002": {"name": "Office Test", "tactics": ["Persistence"]},
    "T1137.003": {"name": "Outlook Forms", "tactics": ["Persistence"]},
    "T1137.004": {"name": "Outlook Home Page", "tactics": ["Persistence"]},
    "T1137.005": {"name": "Outlook Rules", "tactics": ["Persistence"]},
    "T1137.006": {"name": "Add-ins", "tactics": ["Persistence"]},
    "T1542": {"name": "Pre-OS Boot", "tactics": ["Persistence", "Defense Evasion"]},
    "T1542.001": {"name": "System Firmware", "tactics": ["Persistence", "Defense Evasion"]},
    "T1542.002": {"name": "Component Firmware", "tactics": ["Persistence", "Defense Evasion"]},
    "T1542.003": {"name": "Bootkit", "tactics": ["Persistence", "Defense Evasion"]},
    "T1542.004": {"name": "ROMMONkit", "tactics": ["Persistence", "Defense Evasion"]},
    "T1542.005": {"name": "TFTP Boot", "tactics": ["Persistence", "Defense Evasion"]},
    "T1505": {"name": "Server Software Component", "tactics": ["Persistence"]},
    "T1505.001": {"name": "SQL Stored Procedures", "tactics": ["Persistence"]},
    "T1505.002": {"name": "Transport Agent", "tactics": ["Persistence"]},
    "T1505.003": {"name": "Web Shell", "tactics": ["Persistence"]},
    "T1505.004": {"name": "IIS Components", "tactics": ["Persistence"]},
    "T1505.005": {"name": "Terminal Services DLL", "tactics": ["Persistence"]},
    "T1205": {"name": "Traffic Signaling", "tactics": ["Persistence", "Defense Evasion", "Command and Control"]},
    "T1205.001": {"name": "Port Knocking", "tactics": ["Persistence", "Defense Evasion", "Command and Control"]},
    "T1205.002": {"name": "Socket Filters", "tactics": ["Persistence", "Defense Evasion", "Command and Control"]},

    # ── Privilege Escalation ────────────────────────────────────────────────
    "T1548": {"name": "Abuse Elevation Control Mechanism", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1548.001": {"name": "Setuid and Setgid", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1548.002": {"name": "Bypass User Account Control", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1548.003": {"name": "Sudo and Sudo Caching", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1548.004": {"name": "Elevated Execution with Prompt", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1548.005": {"name": "Temporary Elevated Cloud Access", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1134": {"name": "Access Token Manipulation", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1134.001": {"name": "Token Impersonation/Theft", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1134.002": {"name": "Create Process with Token", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1134.003": {"name": "Make and Impersonate Token", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1134.004": {"name": "Parent PID Spoofing", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1134.005": {"name": "SID-History Injection", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1068": {"name": "Exploitation for Privilege Escalation", "tactics": ["Privilege Escalation"]},
    "T1055": {"name": "Process Injection", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.001": {"name": "Dynamic-link Library Injection", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.002": {"name": "Portable Executable Injection", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.003": {"name": "Thread Execution Hijacking", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.004": {"name": "Asynchronous Procedure Call", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.005": {"name": "Thread Local Storage", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.008": {"name": "Ptrace System Calls", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.009": {"name": "Proc Memory", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.011": {"name": "Extra Window Memory Injection", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.012": {"name": "Process Hollowing", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.013": {"name": "Process Doppelganging", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.014": {"name": "VDSO Hijacking", "tactics": ["Privilege Escalation", "Defense Evasion"]},
    "T1055.015": {"name": "ListPlanting", "tactics": ["Privilege Escalation", "Defense Evasion"]},

    # ── Defense Evasion ─────────────────────────────────────────────────────
    "T1140": {"name": "Deobfuscate/Decode Files or Information", "tactics": ["Defense Evasion"]},
    "T1006": {"name": "Direct Volume Access", "tactics": ["Defense Evasion"]},
    "T1480": {"name": "Execution Guardrails", "tactics": ["Defense Evasion"]},
    "T1480.001": {"name": "Environmental Keying", "tactics": ["Defense Evasion"]},
    "T1211": {"name": "Exploitation for Defense Evasion", "tactics": ["Defense Evasion"]},
    "T1222": {"name": "File and Directory Permissions Modification", "tactics": ["Defense Evasion"]},
    "T1222.001": {"name": "Windows File and Directory Permissions Modification", "tactics": ["Defense Evasion"]},
    "T1222.002": {"name": "Linux and Mac File and Directory Permissions Modification", "tactics": ["Defense Evasion"]},
    "T1564": {"name": "Hide Artifacts", "tactics": ["Defense Evasion"]},
    "T1564.001": {"name": "Hidden Files and Directories", "tactics": ["Defense Evasion"]},
    "T1564.002": {"name": "Hidden Users", "tactics": ["Defense Evasion"]},
    "T1564.003": {"name": "Hidden Window", "tactics": ["Defense Evasion"]},
    "T1564.004": {"name": "NTFS File Attributes", "tactics": ["Defense Evasion"]},
    "T1564.005": {"name": "Hidden File System", "tactics": ["Defense Evasion"]},
    "T1564.006": {"name": "Run Virtual Instance", "tactics": ["Defense Evasion"]},
    "T1564.007": {"name": "VBA Stomping", "tactics": ["Defense Evasion"]},
    "T1564.008": {"name": "Email Hiding Rules", "tactics": ["Defense Evasion"]},
    "T1564.009": {"name": "Resource Forking", "tactics": ["Defense Evasion"]},
    "T1564.010": {"name": "Process Argument Spoofing", "tactics": ["Defense Evasion"]},
    "T1564.011": {"name": "Ignore Process Interrupts", "tactics": ["Defense Evasion"]},
    "T1564.012": {"name": "File/Path Exclusions", "tactics": ["Defense Evasion"]},
    "T1562": {"name": "Impair Defenses", "tactics": ["Defense Evasion"]},
    "T1562.001": {"name": "Disable or Modify Tools", "tactics": ["Defense Evasion"]},
    "T1562.002": {"name": "Disable Windows Event Logging", "tactics": ["Defense Evasion"]},
    "T1562.003": {"name": "Impair Command History Logging", "tactics": ["Defense Evasion"]},
    "T1562.004": {"name": "Disable or Modify System Firewall", "tactics": ["Defense Evasion"]},
    "T1562.006": {"name": "Indicator Blocking", "tactics": ["Defense Evasion"]},
    "T1562.007": {"name": "Disable or Modify Cloud Firewall", "tactics": ["Defense Evasion"]},
    "T1562.008": {"name": "Disable or Modify Cloud Logs", "tactics": ["Defense Evasion"]},
    "T1562.009": {"name": "Safe Mode Boot", "tactics": ["Defense Evasion"]},
    "T1562.010": {"name": "Downgrade Attack", "tactics": ["Defense Evasion"]},
    "T1562.011": {"name": "Spoof Security Alerting", "tactics": ["Defense Evasion"]},
    "T1562.012": {"name": "Disable or Modify Linux Audit System", "tactics": ["Defense Evasion"]},
    "T1070": {"name": "Indicator Removal", "tactics": ["Defense Evasion"]},
    "T1070.001": {"name": "Clear Windows Event Logs", "tactics": ["Defense Evasion"]},
    "T1070.002": {"name": "Clear Linux or Mac System Logs", "tactics": ["Defense Evasion"]},
    "T1070.003": {"name": "Clear Command History", "tactics": ["Defense Evasion"]},
    "T1070.004": {"name": "File Deletion", "tactics": ["Defense Evasion"]},
    "T1070.005": {"name": "Network Share Connection Removal", "tactics": ["Defense Evasion"]},
    "T1070.006": {"name": "Timestomp", "tactics": ["Defense Evasion"]},
    "T1070.008": {"name": "Clear Mailbox Data", "tactics": ["Defense Evasion"]},
    "T1070.009": {"name": "Clear Persistence", "tactics": ["Defense Evasion"]},
    "T1202": {"name": "Indirect Command Execution", "tactics": ["Defense Evasion"]},
    "T1036": {"name": "Masquerading", "tactics": ["Defense Evasion"]},
    "T1036.001": {"name": "Invalid Code Signature", "tactics": ["Defense Evasion"]},
    "T1036.003": {"name": "Rename System Utilities", "tactics": ["Defense Evasion"]},
    "T1036.004": {"name": "Masquerade Task or Service", "tactics": ["Defense Evasion"]},
    "T1036.005": {"name": "Match Legitimate Name or Location", "tactics": ["Defense Evasion"]},
    "T1036.006": {"name": "Space after Filename", "tactics": ["Defense Evasion"]},
    "T1036.007": {"name": "Double File Extension", "tactics": ["Defense Evasion"]},
    "T1036.008": {"name": "Masquerade File Type", "tactics": ["Defense Evasion"]},
    "T1036.009": {"name": "Break Process Trees", "tactics": ["Defense Evasion"]},
    "T1556": {"name": "Modify Authentication Process", "tactics": ["Defense Evasion", "Credential Access", "Persistence"]},
    "T1556.001": {"name": "Domain Controller Authentication", "tactics": ["Defense Evasion", "Credential Access", "Persistence"]},
    "T1556.002": {"name": "Password Filter DLL", "tactics": ["Defense Evasion", "Credential Access", "Persistence"]},
    "T1556.003": {"name": "Pluggable Authentication Modules", "tactics": ["Defense Evasion", "Credential Access", "Persistence"]},
    "T1556.004": {"name": "Network Device Authentication", "tactics": ["Defense Evasion", "Credential Access", "Persistence"]},
    "T1556.005": {"name": "Reversible Encryption", "tactics": ["Defense Evasion", "Credential Access", "Persistence"]},
    "T1556.006": {"name": "Multi-Factor Authentication", "tactics": ["Defense Evasion", "Credential Access", "Persistence"]},
    "T1556.007": {"name": "Hybrid Identity", "tactics": ["Defense Evasion", "Credential Access", "Persistence"]},
    "T1556.008": {"name": "Network Provider DLL", "tactics": ["Defense Evasion", "Credential Access", "Persistence"]},
    "T1556.009": {"name": "Conditional Access Policies", "tactics": ["Defense Evasion", "Credential Access", "Persistence"]},
    "T1578": {"name": "Modify Cloud Compute Infrastructure", "tactics": ["Defense Evasion"]},
    "T1578.001": {"name": "Create Snapshot", "tactics": ["Defense Evasion"]},
    "T1578.002": {"name": "Create Cloud Instance", "tactics": ["Defense Evasion"]},
    "T1578.003": {"name": "Delete Cloud Instance", "tactics": ["Defense Evasion"]},
    "T1578.004": {"name": "Revert Cloud Instance", "tactics": ["Defense Evasion"]},
    "T1578.005": {"name": "Modify Cloud Compute Configurations", "tactics": ["Defense Evasion"]},
    "T1112": {"name": "Modify Registry", "tactics": ["Defense Evasion"]},
    "T1601": {"name": "Modify System Image", "tactics": ["Defense Evasion"]},
    "T1601.001": {"name": "Patch System Image", "tactics": ["Defense Evasion"]},
    "T1601.002": {"name": "Downgrade System Image", "tactics": ["Defense Evasion"]},
    "T1599": {"name": "Network Boundary Bridging", "tactics": ["Defense Evasion"]},
    "T1599.001": {"name": "Network Address Translation Traversal", "tactics": ["Defense Evasion"]},
    "T1027": {"name": "Obfuscated Files or Information", "tactics": ["Defense Evasion"]},
    "T1027.001": {"name": "Binary Padding", "tactics": ["Defense Evasion"]},
    "T1027.002": {"name": "Software Packing", "tactics": ["Defense Evasion"]},
    "T1027.003": {"name": "Steganography", "tactics": ["Defense Evasion"]},
    "T1027.004": {"name": "Compile After Delivery", "tactics": ["Defense Evasion"]},
    "T1027.005": {"name": "Indicator Removal from Tools", "tactics": ["Defense Evasion"]},
    "T1027.006": {"name": "HTML Smuggling", "tactics": ["Defense Evasion"]},
    "T1027.007": {"name": "Dynamic API Resolution", "tactics": ["Defense Evasion"]},
    "T1027.008": {"name": "Stripped Payloads", "tactics": ["Defense Evasion"]},
    "T1027.009": {"name": "Embedded Payloads", "tactics": ["Defense Evasion"]},
    "T1027.010": {"name": "Command Obfuscation", "tactics": ["Defense Evasion"]},
    "T1027.011": {"name": "Fileless Storage", "tactics": ["Defense Evasion"]},
    "T1027.012": {"name": "LNK Icon Smuggling", "tactics": ["Defense Evasion"]},
    "T1027.013": {"name": "Encrypted/Encoded File", "tactics": ["Defense Evasion"]},
    "T1647": {"name": "Plist File Modification", "tactics": ["Defense Evasion"]},
    "T1207": {"name": "Rogue Domain Controller", "tactics": ["Defense Evasion"]},
    "T1014": {"name": "Rootkit", "tactics": ["Defense Evasion"]},
    "T1553": {"name": "Subvert Trust Controls", "tactics": ["Defense Evasion"]},
    "T1553.001": {"name": "Gatekeeper Bypass", "tactics": ["Defense Evasion"]},
    "T1553.002": {"name": "Code Signing", "tactics": ["Defense Evasion"]},
    "T1553.003": {"name": "SIP and Trust Provider Hijacking", "tactics": ["Defense Evasion"]},
    "T1553.004": {"name": "Install Root Certificate", "tactics": ["Defense Evasion"]},
    "T1553.005": {"name": "Mark-of-the-Web Bypass", "tactics": ["Defense Evasion"]},
    "T1553.006": {"name": "Code Signing Policy Modification", "tactics": ["Defense Evasion"]},
    "T1218": {"name": "System Binary Proxy Execution", "tactics": ["Defense Evasion"]},
    "T1218.001": {"name": "Compiled HTML File", "tactics": ["Defense Evasion"]},
    "T1218.002": {"name": "Control Panel", "tactics": ["Defense Evasion"]},
    "T1218.003": {"name": "CMSTP", "tactics": ["Defense Evasion"]},
    "T1218.004": {"name": "InstallUtil", "tactics": ["Defense Evasion"]},
    "T1218.005": {"name": "Mshta", "tactics": ["Defense Evasion"]},
    "T1218.007": {"name": "Msiexec", "tactics": ["Defense Evasion"]},
    "T1218.008": {"name": "Odbcconf", "tactics": ["Defense Evasion"]},
    "T1218.009": {"name": "Regsvcs/Regasm", "tactics": ["Defense Evasion"]},
    "T1218.010": {"name": "Regsvr32", "tactics": ["Defense Evasion"]},
    "T1218.011": {"name": "Rundll32", "tactics": ["Defense Evasion"]},
    "T1218.012": {"name": "Verclsid", "tactics": ["Defense Evasion"]},
    "T1218.013": {"name": "Mavinject", "tactics": ["Defense Evasion"]},
    "T1218.014": {"name": "MMC", "tactics": ["Defense Evasion"]},
    "T1216": {"name": "System Script Proxy Execution", "tactics": ["Defense Evasion"]},
    "T1216.001": {"name": "PubPrn", "tactics": ["Defense Evasion"]},
    "T1216.002": {"name": "SyncAppvPublishingServer", "tactics": ["Defense Evasion"]},
    "T1221": {"name": "Template Injection", "tactics": ["Defense Evasion"]},
    "T1127": {"name": "Trusted Developer Utilities Proxy Execution", "tactics": ["Defense Evasion"]},
    "T1127.001": {"name": "MSBuild", "tactics": ["Defense Evasion"]},
    "T1535": {"name": "Unused/Unsupported Cloud Regions", "tactics": ["Defense Evasion"]},
    "T1550": {"name": "Use Alternate Authentication Material", "tactics": ["Defense Evasion", "Lateral Movement"]},
    "T1550.001": {"name": "Application Access Token", "tactics": ["Defense Evasion", "Lateral Movement"]},
    "T1550.002": {"name": "Pass the Hash", "tactics": ["Defense Evasion", "Lateral Movement"]},
    "T1550.003": {"name": "Pass the Ticket", "tactics": ["Defense Evasion", "Lateral Movement"]},
    "T1550.004": {"name": "Web Session Cookie", "tactics": ["Defense Evasion", "Lateral Movement"]},
    "T1497": {"name": "Virtualization/Sandbox Evasion", "tactics": ["Defense Evasion", "Discovery"]},
    "T1497.001": {"name": "System Checks", "tactics": ["Defense Evasion", "Discovery"]},
    "T1497.002": {"name": "User Activity Based Checks", "tactics": ["Defense Evasion", "Discovery"]},
    "T1497.003": {"name": "Time Based Evasion", "tactics": ["Defense Evasion", "Discovery"]},
    "T1620": {"name": "Reflective Code Loading", "tactics": ["Defense Evasion"]},
    "T1622": {"name": "Debugger Evasion", "tactics": ["Defense Evasion", "Discovery"]},

    # ── Credential Access ───────────────────────────────────────────────────
    "T1557": {"name": "Adversary-in-the-Middle", "tactics": ["Credential Access", "Collection"]},
    "T1557.001": {"name": "LLMNR/NBT-NS Poisoning and SMB Relay", "tactics": ["Credential Access", "Collection"]},
    "T1557.002": {"name": "ARP Cache Poisoning", "tactics": ["Credential Access", "Collection"]},
    "T1557.003": {"name": "DHCP Spoofing", "tactics": ["Credential Access", "Collection"]},
    "T1110": {"name": "Brute Force", "tactics": ["Credential Access"]},
    "T1110.001": {"name": "Password Guessing", "tactics": ["Credential Access"]},
    "T1110.002": {"name": "Password Cracking", "tactics": ["Credential Access"]},
    "T1110.003": {"name": "Password Spraying", "tactics": ["Credential Access"]},
    "T1110.004": {"name": "Credential Stuffing", "tactics": ["Credential Access"]},
    "T1555": {"name": "Credentials from Password Stores", "tactics": ["Credential Access"]},
    "T1555.001": {"name": "Keychain", "tactics": ["Credential Access"]},
    "T1555.002": {"name": "Securityd Memory", "tactics": ["Credential Access"]},
    "T1555.003": {"name": "Credentials from Web Browsers", "tactics": ["Credential Access"]},
    "T1555.004": {"name": "Windows Credential Manager", "tactics": ["Credential Access"]},
    "T1555.005": {"name": "Password Managers", "tactics": ["Credential Access"]},
    "T1555.006": {"name": "Cloud Secrets Management Stores", "tactics": ["Credential Access"]},
    "T1212": {"name": "Exploitation for Credential Access", "tactics": ["Credential Access"]},
    "T1187": {"name": "Forced Authentication", "tactics": ["Credential Access"]},
    "T1606": {"name": "Forge Web Credentials", "tactics": ["Credential Access"]},
    "T1606.001": {"name": "Web Cookies", "tactics": ["Credential Access"]},
    "T1606.002": {"name": "SAML Tokens", "tactics": ["Credential Access"]},
    "T1056": {"name": "Input Capture", "tactics": ["Credential Access", "Collection"]},
    "T1056.001": {"name": "Keylogging", "tactics": ["Credential Access", "Collection"]},
    "T1056.002": {"name": "GUI Input Capture", "tactics": ["Credential Access", "Collection"]},
    "T1056.003": {"name": "Web Portal Capture", "tactics": ["Credential Access", "Collection"]},
    "T1056.004": {"name": "Credential API Hooking", "tactics": ["Credential Access", "Collection"]},
    "T1556": {"name": "Modify Authentication Process", "tactics": ["Credential Access", "Defense Evasion", "Persistence"]},
    "T1111": {"name": "Multi-Factor Authentication Interception", "tactics": ["Credential Access"]},
    "T1621": {"name": "Multi-Factor Authentication Request Generation", "tactics": ["Credential Access"]},
    "T1040": {"name": "Network Sniffing", "tactics": ["Credential Access", "Discovery"]},
    "T1003": {"name": "OS Credential Dumping", "tactics": ["Credential Access"]},
    "T1003.001": {"name": "LSASS Memory", "tactics": ["Credential Access"]},
    "T1003.002": {"name": "Security Account Manager", "tactics": ["Credential Access"]},
    "T1003.003": {"name": "NTDS", "tactics": ["Credential Access"]},
    "T1003.004": {"name": "LSA Secrets", "tactics": ["Credential Access"]},
    "T1003.005": {"name": "Cached Domain Credentials", "tactics": ["Credential Access"]},
    "T1003.006": {"name": "DCSync", "tactics": ["Credential Access"]},
    "T1003.007": {"name": "Proc Filesystem", "tactics": ["Credential Access"]},
    "T1003.008": {"name": "/etc/passwd and /etc/shadow", "tactics": ["Credential Access"]},
    "T1528": {"name": "Steal Application Access Token", "tactics": ["Credential Access"]},
    "T1649": {"name": "Steal or Forge Authentication Certificates", "tactics": ["Credential Access"]},
    "T1558": {"name": "Steal or Forge Kerberos Tickets", "tactics": ["Credential Access"]},
    "T1558.001": {"name": "Golden Ticket", "tactics": ["Credential Access"]},
    "T1558.002": {"name": "Silver Ticket", "tactics": ["Credential Access"]},
    "T1558.003": {"name": "Kerberoasting", "tactics": ["Credential Access"]},
    "T1558.004": {"name": "AS-REP Roasting", "tactics": ["Credential Access"]},
    "T1539": {"name": "Steal Web Session Cookie", "tactics": ["Credential Access"]},
    "T1552": {"name": "Unsecured Credentials", "tactics": ["Credential Access"]},
    "T1552.001": {"name": "Credentials In Files", "tactics": ["Credential Access"]},
    "T1552.002": {"name": "Credentials in Registry", "tactics": ["Credential Access"]},
    "T1552.003": {"name": "Bash History", "tactics": ["Credential Access"]},
    "T1552.004": {"name": "Private Keys", "tactics": ["Credential Access"]},
    "T1552.005": {"name": "Cloud Instance Metadata API", "tactics": ["Credential Access"]},
    "T1552.006": {"name": "Group Policy Preferences", "tactics": ["Credential Access"]},
    "T1552.007": {"name": "Container API", "tactics": ["Credential Access"]},
    "T1552.008": {"name": "Chat Messages", "tactics": ["Credential Access"]},

    # ── Discovery ───────────────────────────────────────────────────────────
    "T1087": {"name": "Account Discovery", "tactics": ["Discovery"]},
    "T1087.001": {"name": "Local Account", "tactics": ["Discovery"]},
    "T1087.002": {"name": "Domain Account", "tactics": ["Discovery"]},
    "T1087.003": {"name": "Email Account", "tactics": ["Discovery"]},
    "T1087.004": {"name": "Cloud Account", "tactics": ["Discovery"]},
    "T1010": {"name": "Application Window Discovery", "tactics": ["Discovery"]},
    "T1217": {"name": "Browser Information Discovery", "tactics": ["Discovery"]},
    "T1580": {"name": "Cloud Infrastructure Discovery", "tactics": ["Discovery"]},
    "T1538": {"name": "Cloud Service Dashboard", "tactics": ["Discovery"]},
    "T1526": {"name": "Cloud Service Discovery", "tactics": ["Discovery"]},
    "T1613": {"name": "Container and Resource Discovery", "tactics": ["Discovery"]},
    "T1482": {"name": "Domain Trust Discovery", "tactics": ["Discovery"]},
    "T1083": {"name": "File and Directory Discovery", "tactics": ["Discovery"]},
    "T1615": {"name": "Group Policy Discovery", "tactics": ["Discovery"]},
    "T1654": {"name": "Log Enumeration", "tactics": ["Discovery"]},
    "T1046": {"name": "Network Service Discovery", "tactics": ["Discovery"]},
    "T1135": {"name": "Network Share Discovery", "tactics": ["Discovery"]},
    "T1201": {"name": "Password Policy Discovery", "tactics": ["Discovery"]},
    "T1120": {"name": "Peripheral Device Discovery", "tactics": ["Discovery"]},
    "T1069": {"name": "Permission Groups Discovery", "tactics": ["Discovery"]},
    "T1069.001": {"name": "Local Groups", "tactics": ["Discovery"]},
    "T1069.002": {"name": "Domain Groups", "tactics": ["Discovery"]},
    "T1069.003": {"name": "Cloud Groups", "tactics": ["Discovery"]},
    "T1057": {"name": "Process Discovery", "tactics": ["Discovery"]},
    "T1012": {"name": "Query Registry", "tactics": ["Discovery"]},
    "T1018": {"name": "Remote System Discovery", "tactics": ["Discovery"]},
    "T1518": {"name": "Software Discovery", "tactics": ["Discovery"]},
    "T1518.001": {"name": "Security Software Discovery", "tactics": ["Discovery"]},
    "T1082": {"name": "System Information Discovery", "tactics": ["Discovery"]},
    "T1614": {"name": "System Location Discovery", "tactics": ["Discovery"]},
    "T1614.001": {"name": "System Language Discovery", "tactics": ["Discovery"]},
    "T1016": {"name": "System Network Configuration Discovery", "tactics": ["Discovery"]},
    "T1016.001": {"name": "Internet Connection Discovery", "tactics": ["Discovery"]},
    "T1016.002": {"name": "Wi-Fi Discovery", "tactics": ["Discovery"]},
    "T1049": {"name": "System Network Connections Discovery", "tactics": ["Discovery"]},
    "T1033": {"name": "System Owner/User Discovery", "tactics": ["Discovery"]},
    "T1007": {"name": "System Service Discovery", "tactics": ["Discovery"]},
    "T1124": {"name": "System Time Discovery", "tactics": ["Discovery"]},

    # ── Lateral Movement ────────────────────────────────────────────────────
    "T1210": {"name": "Exploitation of Remote Services", "tactics": ["Lateral Movement"]},
    "T1534": {"name": "Internal Spearphishing", "tactics": ["Lateral Movement"]},
    "T1570": {"name": "Lateral Tool Transfer", "tactics": ["Lateral Movement"]},
    "T1563": {"name": "Remote Service Session Hijacking", "tactics": ["Lateral Movement"]},
    "T1563.001": {"name": "SSH Hijacking", "tactics": ["Lateral Movement"]},
    "T1563.002": {"name": "RDP Hijacking", "tactics": ["Lateral Movement"]},
    "T1021": {"name": "Remote Services", "tactics": ["Lateral Movement"]},
    "T1021.001": {"name": "Remote Desktop Protocol", "tactics": ["Lateral Movement"]},
    "T1021.002": {"name": "SMB/Windows Admin Shares", "tactics": ["Lateral Movement"]},
    "T1021.003": {"name": "Distributed Component Object Model", "tactics": ["Lateral Movement"]},
    "T1021.004": {"name": "SSH", "tactics": ["Lateral Movement"]},
    "T1021.005": {"name": "VNC", "tactics": ["Lateral Movement"]},
    "T1021.006": {"name": "Windows Remote Management", "tactics": ["Lateral Movement"]},
    "T1021.007": {"name": "Cloud Services", "tactics": ["Lateral Movement"]},
    "T1021.008": {"name": "Direct Cloud VM Connections", "tactics": ["Lateral Movement"]},
    "T1080": {"name": "Taint Shared Content", "tactics": ["Lateral Movement"]},

    # ── Collection ──────────────────────────────────────────────────────────
    "T1560": {"name": "Archive Collected Data", "tactics": ["Collection"]},
    "T1560.001": {"name": "Archive via Utility", "tactics": ["Collection"]},
    "T1560.002": {"name": "Archive via Library", "tactics": ["Collection"]},
    "T1560.003": {"name": "Archive via Custom Method", "tactics": ["Collection"]},
    "T1123": {"name": "Audio Capture", "tactics": ["Collection"]},
    "T1119": {"name": "Automated Collection", "tactics": ["Collection"]},
    "T1185": {"name": "Browser Session Hijacking", "tactics": ["Collection"]},
    "T1115": {"name": "Clipboard Data", "tactics": ["Collection"]},
    "T1530": {"name": "Data from Cloud Storage", "tactics": ["Collection"]},
    "T1602": {"name": "Data from Configuration Repository", "tactics": ["Collection"]},
    "T1602.001": {"name": "SNMP (MIB Dump)", "tactics": ["Collection"]},
    "T1602.002": {"name": "Network Device Configuration Dump", "tactics": ["Collection"]},
    "T1213": {"name": "Data from Information Repositories", "tactics": ["Collection"]},
    "T1213.001": {"name": "Confluence", "tactics": ["Collection"]},
    "T1213.002": {"name": "Sharepoint", "tactics": ["Collection"]},
    "T1213.003": {"name": "Code Repositories", "tactics": ["Collection"]},
    "T1005": {"name": "Data from Local System", "tactics": ["Collection"]},
    "T1039": {"name": "Data from Network Shared Drive", "tactics": ["Collection"]},
    "T1025": {"name": "Data from Removable Media", "tactics": ["Collection"]},
    "T1074": {"name": "Data Staged", "tactics": ["Collection"]},
    "T1074.001": {"name": "Local Data Staging", "tactics": ["Collection"]},
    "T1074.002": {"name": "Remote Data Staging", "tactics": ["Collection"]},
    "T1114": {"name": "Email Collection", "tactics": ["Collection"]},
    "T1114.001": {"name": "Local Email Collection", "tactics": ["Collection"]},
    "T1114.002": {"name": "Remote Email Collection", "tactics": ["Collection"]},
    "T1114.003": {"name": "Email Forwarding Rule", "tactics": ["Collection"]},
    "T1113": {"name": "Screen Capture", "tactics": ["Collection"]},
    "T1125": {"name": "Video Capture", "tactics": ["Collection"]},

    # ── Command and Control ─────────────────────────────────────────────────
    "T1071": {"name": "Application Layer Protocol", "tactics": ["Command and Control"]},
    "T1071.001": {"name": "Web Protocols", "tactics": ["Command and Control"]},
    "T1071.002": {"name": "File Transfer Protocols", "tactics": ["Command and Control"]},
    "T1071.003": {"name": "Mail Protocols", "tactics": ["Command and Control"]},
    "T1071.004": {"name": "DNS", "tactics": ["Command and Control"]},
    "T1092": {"name": "Communication Through Removable Media", "tactics": ["Command and Control"]},
    "T1132": {"name": "Data Encoding", "tactics": ["Command and Control"]},
    "T1132.001": {"name": "Standard Encoding", "tactics": ["Command and Control"]},
    "T1132.002": {"name": "Non-Standard Encoding", "tactics": ["Command and Control"]},
    "T1001": {"name": "Data Obfuscation", "tactics": ["Command and Control"]},
    "T1001.001": {"name": "Junk Data", "tactics": ["Command and Control"]},
    "T1001.002": {"name": "Steganography", "tactics": ["Command and Control"]},
    "T1001.003": {"name": "Protocol Impersonation", "tactics": ["Command and Control"]},
    "T1568": {"name": "Dynamic Resolution", "tactics": ["Command and Control"]},
    "T1568.001": {"name": "Fast Flux DNS", "tactics": ["Command and Control"]},
    "T1568.002": {"name": "Domain Generation Algorithms", "tactics": ["Command and Control"]},
    "T1568.003": {"name": "DNS Calculation", "tactics": ["Command and Control"]},
    "T1573": {"name": "Encrypted Channel", "tactics": ["Command and Control"]},
    "T1573.001": {"name": "Symmetric Cryptography", "tactics": ["Command and Control"]},
    "T1573.002": {"name": "Asymmetric Cryptography", "tactics": ["Command and Control"]},
    "T1008": {"name": "Fallback Channels", "tactics": ["Command and Control"]},
    "T1105": {"name": "Ingress Tool Transfer", "tactics": ["Command and Control"]},
    "T1104": {"name": "Multi-Stage Channels", "tactics": ["Command and Control"]},
    "T1095": {"name": "Non-Application Layer Protocol", "tactics": ["Command and Control"]},
    "T1571": {"name": "Non-Standard Port", "tactics": ["Command and Control"]},
    "T1572": {"name": "Protocol Tunneling", "tactics": ["Command and Control"]},
    "T1090": {"name": "Proxy", "tactics": ["Command and Control"]},
    "T1090.001": {"name": "Internal Proxy", "tactics": ["Command and Control"]},
    "T1090.002": {"name": "External Proxy", "tactics": ["Command and Control"]},
    "T1090.003": {"name": "Multi-hop Proxy", "tactics": ["Command and Control"]},
    "T1090.004": {"name": "Domain Fronting", "tactics": ["Command and Control"]},
    "T1219": {"name": "Remote Access Software", "tactics": ["Command and Control"]},
    "T1102": {"name": "Web Service", "tactics": ["Command and Control"]},
    "T1102.001": {"name": "Dead Drop Resolver", "tactics": ["Command and Control"]},
    "T1102.002": {"name": "Bidirectional Communication", "tactics": ["Command and Control"]},
    "T1102.003": {"name": "One-Way Communication", "tactics": ["Command and Control"]},

    # ── Exfiltration ────────────────────────────────────────────────────────
    "T1020": {"name": "Automated Exfiltration", "tactics": ["Exfiltration"]},
    "T1020.001": {"name": "Traffic Duplication", "tactics": ["Exfiltration"]},
    "T1030": {"name": "Data Transfer Size Limits", "tactics": ["Exfiltration"]},
    "T1048": {"name": "Exfiltration Over Alternative Protocol", "tactics": ["Exfiltration"]},
    "T1048.001": {"name": "Exfiltration Over Symmetric Encrypted Non-C2 Protocol", "tactics": ["Exfiltration"]},
    "T1048.002": {"name": "Exfiltration Over Asymmetric Encrypted Non-C2 Protocol", "tactics": ["Exfiltration"]},
    "T1048.003": {"name": "Exfiltration Over Unencrypted Non-C2 Protocol", "tactics": ["Exfiltration"]},
    "T1041": {"name": "Exfiltration Over C2 Channel", "tactics": ["Exfiltration"]},
    "T1011": {"name": "Exfiltration Over Other Network Medium", "tactics": ["Exfiltration"]},
    "T1011.001": {"name": "Exfiltration Over Bluetooth", "tactics": ["Exfiltration"]},
    "T1052": {"name": "Exfiltration Over Physical Medium", "tactics": ["Exfiltration"]},
    "T1052.001": {"name": "Exfiltration over USB", "tactics": ["Exfiltration"]},
    "T1567": {"name": "Exfiltration Over Web Service", "tactics": ["Exfiltration"]},
    "T1567.001": {"name": "Exfiltration to Code Repository", "tactics": ["Exfiltration"]},
    "T1567.002": {"name": "Exfiltration to Cloud Storage", "tactics": ["Exfiltration"]},
    "T1567.003": {"name": "Exfiltration to Text Storage Sites", "tactics": ["Exfiltration"]},
    "T1567.004": {"name": "Exfiltration Over Webhook", "tactics": ["Exfiltration"]},
    "T1029": {"name": "Scheduled Transfer", "tactics": ["Exfiltration"]},
    "T1537": {"name": "Transfer Data to Cloud Account", "tactics": ["Exfiltration"]},

    # ── Impact ──────────────────────────────────────────────────────────────
    "T1531": {"name": "Account Access Removal", "tactics": ["Impact"]},
    "T1485": {"name": "Data Destruction", "tactics": ["Impact"]},
    "T1486": {"name": "Data Encrypted for Impact", "tactics": ["Impact"]},
    "T1565": {"name": "Data Manipulation", "tactics": ["Impact"]},
    "T1565.001": {"name": "Stored Data Manipulation", "tactics": ["Impact"]},
    "T1565.002": {"name": "Transmitted Data Manipulation", "tactics": ["Impact"]},
    "T1565.003": {"name": "Runtime Data Manipulation", "tactics": ["Impact"]},
    "T1491": {"name": "Defacement", "tactics": ["Impact"]},
    "T1491.001": {"name": "Internal Defacement", "tactics": ["Impact"]},
    "T1491.002": {"name": "External Defacement", "tactics": ["Impact"]},
    "T1561": {"name": "Disk Wipe", "tactics": ["Impact"]},
    "T1561.001": {"name": "Disk Content Wipe", "tactics": ["Impact"]},
    "T1561.002": {"name": "Disk Structure Wipe", "tactics": ["Impact"]},
    "T1499": {"name": "Endpoint Denial of Service", "tactics": ["Impact"]},
    "T1499.001": {"name": "OS Exhaustion Flood", "tactics": ["Impact"]},
    "T1499.002": {"name": "Service Exhaustion Flood", "tactics": ["Impact"]},
    "T1499.003": {"name": "Application Exhaustion Flood", "tactics": ["Impact"]},
    "T1499.004": {"name": "Application or System Exploitation", "tactics": ["Impact"]},
    "T1657": {"name": "Financial Theft", "tactics": ["Impact"]},
    "T1495": {"name": "Firmware Corruption", "tactics": ["Impact"]},
    "T1490": {"name": "Inhibit System Recovery", "tactics": ["Impact"]},
    "T1498": {"name": "Network Denial of Service", "tactics": ["Impact"]},
    "T1498.001": {"name": "Direct Network Flood", "tactics": ["Impact"]},
    "T1498.002": {"name": "Reflection Amplification", "tactics": ["Impact"]},
    "T1496": {"name": "Resource Hijacking", "tactics": ["Impact"]},
    "T1489": {"name": "Service Stop", "tactics": ["Impact"]},
    "T1529": {"name": "System Shutdown/Reboot", "tactics": ["Impact"]},
}


# ==============================================================================
# MITRE ATLAS TECHNIQUE MAP (v4)
# ==============================================================================
ATLAS_TECHNIQUE_MAP: Dict[str, Dict] = {
    # ── Reconnaissance ──────────────────────────────────────────────────────
    "AML.T0000": {"name": "ML Model Discovery", "tactics": ["Reconnaissance"]},
    "AML.T0001": {"name": "ML Artifact Collection", "tactics": ["Reconnaissance"]},
    "AML.T0002": {"name": "Active Scanning of ML Services", "tactics": ["Reconnaissance"]},
    "AML.T0012": {"name": "Discover ML Model Ontology", "tactics": ["Reconnaissance"]},
    "AML.T0014": {"name": "Discover ML Artifacts", "tactics": ["Reconnaissance"]},
    "AML.T0036": {"name": "Search for ML Artifacts", "tactics": ["Reconnaissance"]},

    # ── Resource Development ────────────────────────────────────────────────
    "AML.T0003": {"name": "Develop Adversarial ML Attack Tools", "tactics": ["Resource Development"]},
    "AML.T0004": {"name": "Obtain Adversarial ML Attack Implementations", "tactics": ["Resource Development"]},
    "AML.T0017": {"name": "Develop Adversarial ML Attacks", "tactics": ["Resource Development"]},
    "AML.T0037": {"name": "Acquire Public ML Artifacts", "tactics": ["Resource Development"]},
    "AML.T0038": {"name": "Create Proxy ML Model", "tactics": ["Resource Development"]},

    # ── ML Model Access ─────────────────────────────────────────────────────
    "AML.T0005": {"name": "ML Model Access via API", "tactics": ["ML Model Access"]},
    "AML.T0034": {"name": "Physical Environment Access", "tactics": ["ML Model Access"]},
    "AML.T0035": {"name": "ML-Enabled Product or Service", "tactics": ["ML Model Access"]},

    # ── Initial Access ──────────────────────────────────────────────────────
    "AML.T0006": {"name": "Data Injection", "tactics": ["Initial Access"]},
    "AML.T0019": {"name": "Publish Poisoned ML Artifacts", "tactics": ["Initial Access"]},
    "AML.T0039": {"name": "ML Supply Chain Compromise", "tactics": ["Initial Access"]},

    # ── Execution ───────────────────────────────────────────────────────────
    "AML.T0040": {"name": "ML Model Inference API Access", "tactics": ["Execution"]},
    "AML.T0041": {"name": "Prompt Injection", "tactics": ["Execution"]},
    "AML.T0042": {"name": "Unsafe ML Model Deserialization", "tactics": ["Execution"]},

    # ── Persistence ─────────────────────────────────────────────────────────
    "AML.T0020": {"name": "Poison ML Model", "tactics": ["Persistence"]},
    "AML.T0043": {"name": "ML Model Backdoor", "tactics": ["Persistence"]},

    # ── Defense Evasion ─────────────────────────────────────────────────────
    "AML.T0007": {"name": "Evade ML Model", "tactics": ["Defense Evasion"]},
    "AML.T0022": {"name": "Adversarial Example in Physical Domain", "tactics": ["Defense Evasion"]},
    "AML.T0044": {"name": "Full ML Model Replication", "tactics": ["Defense Evasion"]},

    # ── Discovery ───────────────────────────────────────────────────────────
    "AML.T0008": {"name": "Discover ML Model Family", "tactics": ["Discovery"]},
    "AML.T0024": {"name": "Discover ML Model Using Queries", "tactics": ["Discovery"]},

    # ── Collection ──────────────────────────────────────────────────────────
    "AML.T0025": {"name": "Exfiltrate ML Model via Cyber Means", "tactics": ["Collection"]},
    "AML.T0035.001": {"name": "Extract ML Model", "tactics": ["Collection"]},

    # ── ML Attack Staging ───────────────────────────────────────────────────
    "AML.T0009": {"name": "Craft Adversarial Data", "tactics": ["ML Attack Staging"]},
    "AML.T0010": {"name": "ML Model Inference API Exploitation", "tactics": ["ML Attack Staging"]},
    "AML.T0011": {"name": "User Interaction with ML Model", "tactics": ["ML Attack Staging"]},
    "AML.T0029": {"name": "Verify ML Attack", "tactics": ["ML Attack Staging"]},

    # ── Exfiltration ────────────────────────────────────────────────────────
    "AML.T0024.001": {"name": "Infer Training Data Membership", "tactics": ["Exfiltration"]},
    "AML.T0024.002": {"name": "Invert ML Model", "tactics": ["Exfiltration"]},
    "AML.T0031": {"name": "Erode ML Model Integrity", "tactics": ["Exfiltration"]},

    # ── Impact ──────────────────────────────────────────────────────────────
    "AML.T0013": {"name": "Cost Harvesting", "tactics": ["Impact"]},
    "AML.T0015": {"name": "Evade ML Model", "tactics": ["Impact"]},
    "AML.T0029.001": {"name": "Denial of ML Service", "tactics": ["Impact"]},
    "AML.T0032": {"name": "Compromise ML Model Integrity", "tactics": ["Impact"]},
    "AML.T0033": {"name": "Compromise ML Intellectual Property", "tactics": ["Impact"]},
}


# ==============================================================================
# LOOKUP FUNCTIONS
# ==============================================================================

def get_attack_tactic(technique_id: str) -> List[str]:
    """Return list of tactic names for a given ATT&CK technique ID."""
    info = ATTACK_TECHNIQUE_MAP.get(technique_id)
    if not info and "." in technique_id:
        parent = technique_id.split(".")[0]
        info = ATTACK_TECHNIQUE_MAP.get(parent)
    return info["tactics"] if info else ["Other"]


def get_attack_name(technique_id: str) -> str:
    """Return the technique name for a given ATT&CK technique ID."""
    info = ATTACK_TECHNIQUE_MAP.get(technique_id)
    if not info and "." in technique_id:
        parent = technique_id.split(".")[0]
        info = ATTACK_TECHNIQUE_MAP.get(parent)
    return info["name"] if info else technique_id


def get_atlas_tactic(technique_id: str) -> List[str]:
    """Return list of tactic names for a given ATLAS technique ID."""
    info = ATLAS_TECHNIQUE_MAP.get(technique_id)
    if not info and "." in technique_id:
        parent = technique_id.rsplit(".", 1)[0]
        info = ATLAS_TECHNIQUE_MAP.get(parent)
    return info["tactics"] if info else ["Other"]


def get_atlas_name(technique_id: str) -> str:
    """Return the technique name for a given ATLAS technique ID."""
    info = ATLAS_TECHNIQUE_MAP.get(technique_id)
    if not info and "." in technique_id:
        parent = technique_id.rsplit(".", 1)[0]
        info = ATLAS_TECHNIQUE_MAP.get(parent)
    return info["name"] if info else technique_id


def is_valid_technique_id(technique_id: str) -> bool:
    """Check if a technique ID exists in either ATT&CK or ATLAS."""
    if technique_id in ATTACK_TECHNIQUE_MAP:
        return True
    if technique_id in ATLAS_TECHNIQUE_MAP:
        return True
    # Check parent for sub-techniques
    if "." in technique_id:
        parent = technique_id.split(".")[0]
        return parent in ATTACK_TECHNIQUE_MAP or parent in ATLAS_TECHNIQUE_MAP
    return False
